import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="text-red-800 bg-purple-200 py-3">
          <h2>Home layout</h2>
          <Link href={"/"}>Goto Home</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
